export const homeTransactionsData: TransactionSchema[] = [
  {
    id: "sept-1",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 200.0,
    date: "03 Sep",
    month: "SEP",
  },
  {
    id: "sept-2",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "03 Sep",
    month: "SEP",
  },
  {
    id: "sept-3",
    icon: "data-matrix-scan",
    transferAccount: "To Chicken Rice Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 3.5,
    date: "03 Sep",
    month: "SEP",
  },
  {
    id: "sept-4",
    icon: "account-arrow-left",
    transferAccount: "From Sarah",
    transferAction: "Transfer",
    add: true,
    amount: 50.0,
    date: "02 Sep",
    month: "SEP",
  },
  {
    id: "sept-5",
    icon: "data-matrix-scan",
    transferAccount: "To Duck Rice Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 3.5,
    date: "02 Sep",
    month: "SEP",
  },
];

export const transactionsDataSeptember: TransactionSchema[] = [
  {
    id: "sept-1",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 200.0,
    date: "03 Sep",
    month: "SEP",
  },
  {
    id: "sept-2",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "03 Sep",
    month: "SEP",
  },
  {
    id: "sept-3",
    icon: "data-matrix-scan",
    transferAccount: "To Chicken Rice Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 3.5,
    date: "03 Sep",
    month: "SEP",
  },
  {
    id: "sept-4",
    icon: "account-arrow-left",
    transferAccount: "From Sarah",
    transferAction: "Transfer",
    add: true,
    amount: 50.0,
    date: "02 Sep",
    month: "SEP",
  },
  {
    id: "sept-5",
    icon: "data-matrix-scan",
    transferAccount: "To Duck Rice Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 3.5,
    date: "02 Sep",
    month: "SEP",
  },
  {
    id: "sept-6",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 100.0,
    date: "01 Sep",
    month: "SEP",
  },
  {
    id: "sept-7",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "01 Sep",
    month: "SEP",
  },
  {
    id: "sept-8",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "01 Sep",
    month: "SEP",
  },
];

export const transactionsDataAugust: TransactionSchema[] = [
  {
    id: "aug-1",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 50.0,
    date: "31 Aug",
    month: "AUG",
  },
  {
    id: "aug-2",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 30.0,
    date: "25 Aug",
    month: "AUG",
  },
  {
    id: "aug-3",
    icon: "data-matrix-scan",
    transferAccount: "To Bubble Tea Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 7.5,
    date: "25 Aug",
    month: "AUG",
  },
  {
    id: "aug-4",
    icon: "account-arrow-left",
    transferAccount: "From Alex",
    transferAction: "Transfer",
    add: true,
    amount: 10.0,
    date: "25 Aug",
    month: "AUG",
  },
  {
    id: "aug-5",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "25 Aug",
    month: "AUG",
  },
  {
    id: "aug-6",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 100.0,
    date: "18 Aug",
    month: "AUG",
  },
  {
    id: "aug-7",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 10.0,
    date: "18 Aug",
    month: "AUG",
  },
  {
    id: "aug-8",
    icon: "data-matrix-scan",
    transferAccount: "To NUS",
    transferAction: "Scan/Pay",
    add: false,
    amount: 150,
    date: "18 Aug",
    month: "AUG",
  },
];

export const transactionsDataJuly: TransactionSchema[] = [
  {
    id: "july-1",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 200.0,
    date: "29 Jul",
    month: "JUL",
  },
  {
    id: "july-2",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "29 Jul",
    month: "JUL",
  },
  {
    id: "july-3",
    icon: "data-matrix-scan",
    transferAccount: "To Chicken Rice Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 3.5,
    date: "28 Jul",
    month: "JUL",
  },
  {
    id: "july-4",
    icon: "account-arrow-left",
    transferAccount: "From Sarah",
    transferAction: "Transfer",
    add: true,
    amount: 50.0,
    date: "28 Jul",
    month: "JUL",
  },
  {
    id: "july-5",
    icon: "data-matrix-scan",
    transferAccount: "To Duck Rice Stall",
    transferAction: "Scan/Pay",
    add: false,
    amount: 3.5,
    date: "27 Jul",
    month: "JUL",
  },
  {
    id: "july-6",
    icon: "wallet-plus",
    transferAccount: "From Bank",
    transferAction: "Top Up",
    add: true,
    amount: 100.0,
    date: "27 Jul",
    month: "JUL",
  },
  {
    id: "july-7",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "27 Jul",
    month: "JUL",
  },
  {
    id: "july-8",
    icon: "account-arrow-right",
    transferAccount: "To Sarah",
    transferAction: "Transfer",
    add: false,
    amount: 50.0,
    date: "27 Jul",
    month: "JUL",
  },
];
